# Generated by Django 6.0.2 on 2026-03-14 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=30, verbose_name='Tipo de equipo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Número de serie')),
                ('operative_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sistema operativo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_service', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo'), (2, 'En mantenimiento')], default=1)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
