# Generated by Django 6.0.2 on 2026-02-26 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('operative_system', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_service', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
