# Generated by Django 6.0.2 on 2026-03-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='machine_id',
        ),
    ]
