# Generated by Django 6.0.2 on 2026-03-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_asset_machine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
    ]
