# Generated by Django 6.0.2 on 2026-03-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_remove_asset_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)'),
        ),
    ]
