# Generated by Django 6.0.2 on 2026-03-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_cpu_asset_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de serie'),
        ),
    ]
