# Generated by Django 6.0.2 on 2026-04-19 02:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_asset_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField()),
                ('hostname', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('operative_system', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=150, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('last_service', models.DateTimeField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
