# Generated by Django 6.0.2 on 2026-09-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_assethistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethistory',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='assethistory',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='asset.asset', verbose_name='Equipo'),
            preserve_default=False,
        ),
    ]
