# Generated by Django 6.0.2 on 2026-05-16 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0002_tickethistory_alter_ticket_resolution_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSessionAI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_description', models.TextField()),
                ('ai_response', models.TextField()),
                ('detected_priority', models.PositiveSmallIntegerField(default=2)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('solved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('solved', 'Resuelta'), ('escalated', 'Escalada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_support_sessions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_support_session', to='ticket.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'IA')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_support.supportsessionai')),
            ],
        ),
    ]
