# Generated by Django 6.0.2 on 2026-05-17 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_support', '0001_initial'),
        ('asset', '0006_assethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsessionai',
            name='ai_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportsessionai',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='asset.asset'),
        ),
    ]
