# Generated by Django 6.0.2 on 2026-05-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_support', '0002_supportsessionai_ai_diagnosis_supportsessionai_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportsessionai',
            old_name='ai_diagnosis',
            new_name='diagnosis',
        ),
    ]
