# Generated by Django 6.0.2 on 2026-02-26 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
