# Generated by Django 6.0.2 on 2026-06-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_verified_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
    ]
