# Generated by Django 6.0.2 on 2026-02-27 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_time', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='support_session_ai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_description', models.CharField(max_length=100)),
                ('ai_response', models.CharField(max_length=100, null=True)),
                ('suggestions', models.CharField(max_length=100, null=True)),
                ('user_attemp', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_session', to='ticket.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Detail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=100)),
                ('diagnostic', models.CharField(max_length=100, null=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ticket.ticket')),
            ],
        ),
    ]
