# Generated by Django 6.0.2 on 2026-05-02 01:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.UUIDField()),
                ('status', models.SmallIntegerField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Abierto'), (2, 'En proceso'), (3, 'Cerrado')], default=1),
        ),
    ]
