# Generated by Django 6.0.2 on 2026-05-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='support_session_ai',
        ),
    ]
